### ISSUE TITLE
Is the project still maintained?

### ISSUE THREAD

**Issue by Blankeer** [sgolovine/fav.sh#1]
I found the bookmark management chrome extension from Google and found it here. I want a based in "gist" solution. This project reluctantly meet the demand.Thank you for your open source.Is this full the code? and is the project still maintained?
Thanks

**Comment by sgolovine** [comment]
Hey, sorry for the super super late reply. I just recently rebooted this project and decided that rather than refactor the code, I am going to rebuild the entire extension from the ground up. 

If you would like to contribute or follow the rebuilding process you can check it out on the `rebuild` branch of this repository.
